-- disables all current tags
UPDATE interests_tags set active = false;

-- adds new pt-br top tags
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('saúde', 'top', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('autoconhecimento', 'top', 'pt-BR', 1, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('mindfulness', 'top', 'pt-BR', 2, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('meditação', 'top', 'pt-BR', 3, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('consciência', 'top', 'pt-BR', 4, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('alimentação', 'top', 'pt-BR', 5, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('alimentaçãosaudável', 'top', 'pt-BR', 6, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('alimentaçãovegetariana', 'top', 'pt-BR', 7, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('alimentaçãovegana', 'top', 'pt-BR', 8, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('alimentaçãoviva', 'top', 'pt-BR', 9, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('educacão', 'top', 'pt-BR', 10, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('consumoconsciente', 'top', 'pt-BR', 11, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('reciclagem', 'top', 'pt-BR', 12, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('permacultura', 'top', 'pt-BR', 13, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('energialimpa', 'top', 'pt-BR', 14, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('economiasolidaria', 'top', 'pt-BR', 15, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('projetossociais', 'top', 'pt-BR', 16, true);

-- adds new pt-BR secondary tags
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('natureza', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('água', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('sustentabilidade', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('animais', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('ecologia', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('agroecologia', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('transição', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('preservação', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('agrofloresta', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('educaçãoambiental', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('ativismo', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('regeneração', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('povosnativos', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('moedassociais', 'secondary', 'pt-BR', 0, true);

-- adds the rest of the new secondary tags
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('yoga', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('arte', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('chakras', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('música', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('saúde', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('paz', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('natureza', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('mindfulness', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('local', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('performance', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('bemestar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('bio', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('pintura', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('energia', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('vegano', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('eco', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('equilíbrio', 'secondary', 'pt-BR', 0, true);
-- INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('água', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('economia', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('sustentabilidade', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('vivo', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('cuidado', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('solar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('jardim', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('urbano', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('meditação', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('vegetariano', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('política', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('consumoconsciente', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('agricultura', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('consciência', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('desapego', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('meioambiente', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('proteção', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('veganismo', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('áudiovisual', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('ecológico', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('reserva', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('mata', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('movimento', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('cultural', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('familiar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('jardinagem', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('ONG', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('faaavocemesmo', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('feira', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('reciclar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('floresta', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('biológico', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('alimento', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('cuidar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('horta', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('exposição', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('doação', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('compartilhar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('holístico', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('economiacircular', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('feitoemcasa', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('caseiro', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('energialimpa', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('permacultura', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('consciente', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('ambiental', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('cru', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('DIY', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('impacto', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('produtor', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('preservação', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('documentário', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('agrofloresta', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('plantar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('hidráulica', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('protesto', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('coletivo', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('proteger', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('doar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('cultivar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('bairro', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('pegada', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('preservar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('nativo', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('manifestação', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('restaurar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('regar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('economiasolidária', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('desapegar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('limpo', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('intervenção', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('desapegar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('compostagem', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('associação', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('ativismo', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('semear', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('recuperar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('reaproveitar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('reduzir', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('bioconstrução', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('colaborativo', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('agriculturasintópica', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('regeneração', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('inclusivo', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('eólica', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('comunitário', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('sistêmico', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('regenerativo', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('renovável', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('trocar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('adubação', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('ecovila', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('evento', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('ecologiaprofunda', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('composto', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('compartilhado', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('biodigestor', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('boicote', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('petição', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('povostradicionais', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('povosnativos', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('consertar', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('sintrópico', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('moedassociais', 'secondary', 'pt-BR', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('moedascomplementares', 'secondary', 'pt-BR', 0, true);

-- adds new en-US top tags

INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('health', 'top', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('self knowledge', 'top', 'en-US', 1, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('mindfulness', 'top', 'en-US', 2, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('meditation', 'top', 'en-US', 3, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('conscience', 'top', 'en-US', 4, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('food', 'top', 'en-US', 5, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('healthy eating', 'top', 'en-US', 6, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('vegetarian food', 'top', 'en-US', 7, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('vegan food', 'top', 'en-US', 8, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('live food', 'top', 'en-US', 9, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('education', 'top', 'en-US', 10, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('conscious consumption', 'top', 'en-US', 11, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('recycling', 'top', 'en-US', 12, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('permaculture', 'top', 'en-US', 13, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('clean energy', 'top', 'en-US', 14, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('solidarity economy', 'top', 'en-US', 15, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('social projects', 'top', 'en-US', 16, true);

-- adds new en-US secondary tags
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('nature', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('water', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('sustainability', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('animals', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('ecology', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('agroecology', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('transition', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('preservation', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('agroforestry', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('environmental education', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('activism', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('regeneration', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('native peoples', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('social currencies', 'secondary', 'en-US', 0, true);

-- adds the rest of the new secondary tags
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('yoga', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('art', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('chakras', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('song', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('health', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('peace', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('nature', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('mindfulness', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('local', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('performance', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('welfare', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('bio', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('painting', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('energy', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('vegan', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('echo', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('balance', 'secondary', 'en-US', 0, true);
-- INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('água', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('economy', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('sustainability', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('alive', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('caution', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('solar', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('garden', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('urban', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('meditation', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('vegetarian', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('policy', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('conscious consumption', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('agriculture', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('conscience', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('detachment', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('environment', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('protection', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('veganism', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('audio-visual', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('ecological', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('reserve', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('woods', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('movement', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('cultural', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('familiar', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('gardening', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('NGO', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('do it yourself', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('fair', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('recycle', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('forest', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('biological', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('food', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('care', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('vegetable garden', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('exposure', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('donation', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('share', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('holístico', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('circular economy', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('homemade', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('house made', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('clean energy', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('permaculture', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('conscious', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('environmental', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('cru', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('do it yourself', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('impact', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('producer', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('preservation', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('documentary', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('agroforestry', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('plant', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('hydraulic', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('protest', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('collective', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('protect', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('donate', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('grow crops', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('district', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('footprint', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('preserve', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('native', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('manifestation', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('restore', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('water', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('solidarity economy', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('let go', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('clean', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('intervention', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('let go', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('compost', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('association', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('activism', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('sow', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('recover', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('reuse', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('reduce', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('bioconstruction', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('collaborative', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('symtopic agriculture', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('regeneration', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('inclusive', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('wind', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('community', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('systemic', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('regenerative', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('renewable', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('replacement', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('fertilizing', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('ecovillage', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('event', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('deep ecology', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('compound', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('shared', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('biodigestor', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('boycott', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('petition', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('traditional peoples', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('native peoples', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('repair', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('syntropic', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('social currencies', 'secondary', 'en-US', 0, true);
INSERT INTO interests_tags (name, type, language, tag_order, active) VALUES ('complementary coins', 'secondary', 'en-US', 0, true);