name: CI
on:
  pull_request:
    branches:
      - staging

jobs:
  devmagic_staging_deploy:
    name: Beta deploy on DevMagic's server
    runs-on: ubuntu-latest
    steps:      
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEVMAGIC_SSH_HOST }} 
          >> ~/.ssh/known_hosts
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEVMAGIC_SSH_PRIVATE_KEY }} 
      - run:> ssh ubuntu@${{ secrets.DEVMAGIC_SSH_HOST }} << EOSSH
            . ~/.nvm/nvm.sh
            cd /home/ubuntu/ootopia-api
            git pull origin staging
            npm ci
            npm run build
            pm2 delete ootopia-api-staging
            pm2 start dist/main.js --name "ootopia-api-staging"
            EOSSH
