name: Build and run tests

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 10.16.3
        cache: 'npm'
    - run: npm i
    # - run: npm test

  deploy_staging:
    if: contains( github.ref, 'staging')
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    env:
        PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        HOSTNAME : ${{ secrets.HOSTNAME }}
        USER_NAME : ${{ secrets.USER_NAME }}
    steps:
      - name: create-firebase-admin-sdk
        id: create-firebase-admin-sdk
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "ootopia-firebase-adminsdk.json"
          json: ${{ secrets.FIREBASE_ADMIN_SDK }}
      - run: echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      - run: ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} uptime
      - run: |
          ssh -i private_key ${USER_NAME}@${HOSTNAME} '
          . ~/.nvm/nvm.sh &&
          cd ootopia-api &&
          git pull origin staging &&
          npm ci &&
          npm run build &&
          pm2 delete ootopia-api-staging &&
          pm2 start dist/main.js --name "ootopia-api-staging"
          '